#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jun 24 17:21:57 MST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
